### ISSUE TITLE
How does this relate to the Civic Tech Info Finder?

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/hack-requests#7]
Just wondering how this repo fits in with the [Civic Tech Info Finder](http://www.codeforamerica.org/geeks/civicissues), if at all. Perhaps add to the readme to reference the Civic Tech Info Finder?

**Comment by ondrae** [comment]
I'm going to start using this repo to collect hack requests as GitHub Issues. Then they'll start to appear on the Issue Finder.
