### ISSUE TITLE
Ferguson Library Website Help

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/hack-requests#8]
We got a Tweet from Ferguson
![screen shot 2014-12-01 at 2 12 44 pm](https://cloud.githubusercontent.com/assets/595778/5254309/31234c3c-7964-11e4-8690-7e1db8463623.png)
https://twitter.com/sugarleg11/status/538767821258620929

[Their website](http://www.ferguson.lib.mo.us/) does need a lot of help though.

This particular library is important though. As Ferguson has been rocked by police brutality and institutional racism, the local schools have all been closed. The library stayed open to take kids in, which is being discussed in [this AMA thread](http://www.reddit.com/r/IAmA/comments/2ns2tb/i_am_ferguson_public_library_director_in_ferguson/cmgemts).

Anyone want to help?

**Comment by andrewmaier** [comment]
Who would be our point of contact at the library? And are there any specifics on a budget/timeline?

**Comment by ondrae** [comment]
I know you saw it already @andrewmaier but people are figuring it all out in the Twitter thread. https://twitter.com/sugarleg11/status/538767821258620929
